name: run-tracker

on:
  workflow_dispatch:


jobs:
  run-tracker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
     
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: 'xformation/xformation-alertmanager-ui-plugin'
          path: './tracker'

      - name: Restore cache for tracker
        id: cache-radius-tracker
        uses: actions/cache/restore@v4        
        with: 
          key: cache-radius-tracker-${{hashFiles('radius-tracker.config.js')}}
          path: radius-tracker-cache/cache
          restore-keys: |
            cache-radius-tracker-${{hashFiles('radius-tracker.config.js')}}

      - name: Run the tracker
        run: |
          npx radius-tracker timelines ./radius-tracker.config.js

      - name: Generate static site
        run: |
          npx radius-tracker report --database usages.sqlite.gz

      - name: Save cache for tracker
        uses: actions/cache/save@v4        
        with: 
          key: cache-radius-tracker-${{hashFiles('radius-tracker.config.js')}}-${{github.run_id}}    
          path: radius-tracker-cache/cache          