name: run-tracker

on:
  workflow_dispatch:

jobs:
  run-tracker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
     
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: 'xformation/xformation-alertmanager-ui-plugin'
          path: './tracker'

      - name: Restore cache for tracker
        uses: actions/cache/restore@v4        
        with: 
          key: radius-tracker-cache     
          path: radius-tracker-cache

      - name: Run the tracker
        run: |
          npx radius-tracker timelines ./radius-tracker.config.js

      - name: Generate static site
        run: |
          npx radius-tracker report --database usages.sqlite.gz

      - name: Save cache for tracker
        uses: actions/cache/save@v4        
        with: 
          key: radius-tracker-cache     
          path: radius-tracker-cache          