name: run-tracker

on:
  workflow_dispatch:

jobs:
  run-tracker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'xformation/xformation-alertmanager-ui-plugin'
          path: './tracker'